name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:lib

      - name: Pack
        run: npm run pack

      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${{ secrets.Token }}" >> .npmrc
          npm publish --access public
